# Generated by Django 3.2.3 on 2021-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cd',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='price',
            field=models.FloatField(),
        ),
    ]
