# Generated by Django 3.2.3 on 2021-06-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0002_auto_20210603_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
