# Generated by Django 3.2.3 on 2021-06-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vinyl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=128)),
                ('artist', models.CharField(blank=True, max_length=128, null=True)),
                ('cover', models.ImageField(upload_to='img')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=128, null=True)),
                ('produce_area', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('second_hand', models.BooleanField()),
                ('remain', models.IntegerField()),
            ],
            options={
                'verbose_name': '专辑名',
                'verbose_name_plural': '专辑名',
                'ordering': ['name'],
                'unique_together': {('barcode', 'produce_area', 'cost')},
            },
        ),
        migrations.CreateModel(
            name='cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=128)),
                ('artist', models.CharField(blank=True, max_length=128, null=True)),
                ('cover', models.ImageField(upload_to='img')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=128, null=True)),
                ('produce_area', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('seal_off', models.BooleanField()),
                ('explicit', models.BooleanField()),
                ('remain', models.IntegerField()),
            ],
            options={
                'verbose_name': '专辑名',
                'verbose_name_plural': '专辑名',
                'ordering': ['name'],
                'unique_together': {('barcode', 'produce_area', 'cost')},
            },
        ),
    ]
