# Generated by Django 3.2.3 on 2021-06-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderlist',
        ),
    ]
