# Generated by Django 3.2.3 on 2021-06-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_orderlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderlist',
        ),
    ]
