# Generated by Django 3.2.3 on 2021-06-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list', '0004_delete_orderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=5)),
                ('mark', models.BooleanField()),
                ('cd', models.BooleanField()),
                ('amount', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('tar', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('produce_area', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '订单',
                'ordering': ['time'],
            },
        ),
    ]
