# Generated by Django 3.2.3 on 2021-06-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_userorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userorder',
        ),
    ]
