# Generated by Django 3.2.3 on 2021-06-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_userorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='cost',
            field=models.FloatField(),
        ),
    ]
